import type { UiAssetManifest } from '../types.js';

export const FX_UI_ASSET_MANIFEST: UiAssetManifest = {
  family: 'fx',
  assets: [
    {
      id: 'ui.fx.mistWispSoft01',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'mist_wisp_soft_01',
      intendedUse: 'Soft mist wisp sprite for ambient underlay drift.',
      screenFamilies: ['hero', 'world', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/mist_wisp_soft_01.png',
      notes: ['Atmosphere base family for low-motion scenic breathing.'],
    },
    {
      id: 'ui.fx.mistWispSoft02',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'mist_wisp_soft_02',
      intendedUse: 'Companion mist variant to avoid repetition in loops.',
      screenFamilies: ['hero', 'world', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/mist_wisp_soft_02.png',
      notes: ['Pairs with 01 for layered atmosphere cadence.'],
    },
    {
      id: 'ui.fx.dustMoteSoft01',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'dust_mote_soft_01',
      intendedUse: 'Ambient dust mote for subtle movement in calm scenes.',
      screenFamilies: ['hero', 'world', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/dust_mote_soft_01.png',
      notes: ['Supports sacred shimmer without sharp sparkle edges.'],
    },
    {
      id: 'ui.fx.dustMoteSoft02',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'dust_mote_soft_02',
      intendedUse: 'Second dust mote variant for distribution diversity.',
      screenFamilies: ['hero', 'world', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/dust_mote_soft_02.png',
      notes: ['Companion for soft motes in medium/high quality.'],
    },
    {
      id: 'ui.fx.haloSoft01',
      family: 'fx',
      subfamily: 'halo',
      status: 'planned-missing',
      logicalName: 'halo_soft_01',
      intendedUse: 'Soft halo under hero focal elements and ritual anchors.',
      screenFamilies: ['hero', 'ritual', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/halos/halo_soft_01.png',
      notes: ['Primary sacred glow family for hero underlays.'],
    },
    {
      id: 'ui.fx.haloRing01',
      family: 'fx',
      subfamily: 'halo',
      status: 'planned-missing',
      logicalName: 'halo_ring_01',
      intendedUse: 'Ring halo for selection emphasis and hero orbiting accents.',
      screenFamilies: ['hero', 'ritual', 'dense'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/halos/halo_ring_01.png',
      notes: ['Supports selection underlay and ritual ring moments.'],
    },
    {
      id: 'ui.fx.sparkGlint01',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'spark_glint_01',
      intendedUse: 'Sharp glint particle for brief recommendation highlights.',
      screenFamilies: ['dense', 'global', 'hero'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/spark_glint_01.png',
      notes: ['Used in sparse bursts to avoid over-noise in readable UI.'],
    },
    {
      id: 'ui.fx.sparkEmber01',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'spark_ember_01',
      intendedUse: 'Warm ember particle for forge/ritual focused moments.',
      screenFamilies: ['module', 'ritual', 'hero'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/spark_ember_01.png',
      notes: ['Complements forge-adjacent hero accents and bursts.'],
    },
    {
      id: 'ui.fx.fireflySoft01',
      family: 'fx',
      subfamily: 'particle',
      status: 'planned-missing',
      logicalName: 'firefly_soft_01',
      intendedUse: 'Firefly-like ambient point light for world drift scenes.',
      screenFamilies: ['world', 'hero', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/particles/firefly_soft_01.png',
      notes: ['World atmosphere particle; respects reduced-motion gating later.'],
    },
    {
      id: 'ui.fx.lightStreakSoft01',
      family: 'fx',
      subfamily: 'swash',
      status: 'planned-missing',
      logicalName: 'light_streak_soft_01',
      intendedUse: 'Soft light streak swash for transitions and emphasis sweeps.',
      screenFamilies: ['hero', 'global', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/swashes/light_streak_soft_01.png',
      notes: ['Reusable brush-light accent for sacred shimmer moments.'],
    },
    {
      id: 'ui.fx.brushSwashRecommendation01',
      family: 'fx',
      subfamily: 'swash',
      status: 'planned-missing',
      logicalName: 'brush_swash_recommendation_01',
      intendedUse: 'Recommendation underlay swash behind advisor labels.',
      screenFamilies: ['dense', 'global', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/swashes/brush_swash_recommendation_01.png',
      notes: ['Dedicated recommendation swash; text remains DOM-rendered.'],
    },
    {
      id: 'ui.fx.brushSwashSelection01',
      family: 'fx',
      subfamily: 'swash',
      status: 'planned-missing',
      logicalName: 'brush_swash_selection_01',
      intendedUse: 'Selection underlay swash for focused picks and active rows.',
      screenFamilies: ['dense', 'module', 'hero'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/fx/swashes/brush_swash_selection_01.png',
      notes: ['Selection family for high-clarity but low-noise emphasis.'],
    },
  ],
};
