import type { RunCompassSurfaceV2 } from '../../../src/systems/ui/runCompass/types.js';

export function makeRunCompassV2Fixture(overrides: Partial<RunCompassSurfaceV2> = {}): RunCompassSurfaceV2 {
  const base: RunCompassSurfaceV2 = {
    version: 2,
    generatedAt: 123,
    mode: 'live',
    milestone: {
      id: 'attemptable:qi_condensation:trial_novices_clearing',
      label: 'Resolve Novice Clearing',
      detail: 'Minimum gate requirements are met.',
      state: 'attemptable',
      currentRealmLabel: 'Qi Condensation',
      nextRealmLabel: 'Foundation Establishment',
      contextLine: 'Qi Condensation -> Foundation Establishment',
      chapterLine: 'Current city: Pinewind Hamlet',
    },
    primaryBlocker: {
      kind: 'attempt_gate_now',
      label: 'Gate can be attempted',
      detail: 'Minimum gate conditions are satisfied. Challenge the threshold.',
      severity: 'success',
      source: 'trial_lifecycle',
      confidence: 'high',
    },
    primaryRoute: {
      id: 'attempt-gate',
      label: 'Attempt Gate Trial',
      actionLabel: 'Attempt Gate Trial',
      detail: 'Challenge the gate now.',
      destinationLabel: 'Gate Trial',
      target: { kind: 'world_module', cityId: 'city_pinewind_hamlet', moduleKey: 'gateTrial' },
      blocked: false,
      blockedReason: null,
      expectedDeltaLabel: 'Gate result updates.',
      source: 'trial_lifecycle',
      priority: 80,
    },
    secondaryRoutes: [
      {
        id: 'secondary-cultivation',
        label: 'Cultivation',
        actionLabel: 'Cultivation',
        detail: 'Return to the cultivation threshold view.',
        destinationLabel: 'Cultivation',
        target: { kind: 'tab', tab: 'cultivation' },
        blocked: false,
        blockedReason: null,
        expectedDeltaLabel: null,
        source: 'progression',
        priority: 90,
      },
      {
        id: 'secondary-forge',
        label: 'Forge Floor',
        actionLabel: 'Open Forge',
        detail: 'Raise the equipment floor before trying again.',
        destinationLabel: 'Forge',
        target: { kind: 'world_module', cityId: 'city_pinewind_hamlet', moduleKey: 'forge' },
        blocked: false,
        blockedReason: null,
        expectedDeltaLabel: 'Forge floor improves.',
        source: 'readiness',
        priority: 40,
      },
    ],
    readiness: {
      score: 74,
      label: 'Viable',
      band: 'minimum_met_below_recommended',
      diagnosisLabel: 'Underprepared',
      primaryShortfallLabel: 'Medicine floor thin',
      rows: [
        {
          id: 'qi',
          label: 'Qi threshold',
          detail: 'Qi is ready for the next threshold.',
          tone: 'success',
        },
        {
          id: 'readiness-band',
          label: 'Gate readiness',
          detail: 'Medicine floor is thin.',
          tone: 'warning',
        },
      ],
    },
    currentCity: {
      cityId: 'city_pinewind_hamlet',
      cityName: 'Pinewind Hamlet',
      visibleModuleKeys: ['outskirts', 'gateTrial', 'manualPavilion', 'apothecary', 'forge', 'bounties', 'expeditions'],
      recommendedModuleKey: 'gateTrial',
    },
    currentGate: {
      trialId: 'trial_novices_clearing',
      gateLabel: 'Novice Clearing',
      fromRealmLabel: 'Qi Condensation',
      toRealmLabel: 'Foundation Establishment',
      gateProofItemId: 'gate_foundation_pill',
      gateProofItemName: 'Gate Foundation Pill',
      lifecycleState: 'available',
      resolved: false,
      canAttempt: true,
      canBreakthrough: false,
      failSafeAvailable: false,
    },
    safetyNet: {
      state: 'available',
      label: 'Safety Net available',
      detail: 'Repeated eligible defeats can resolve the gate through city Merit support.',
      progressLine: 'Eligible defeats 3/3',
      target: { kind: 'world_module', cityId: 'city_pinewind_hamlet', moduleKey: 'gateTrial' },
    },
    prestigeHint: {
      state: 'available',
      label: 'Reincarnation viable',
      detail: 'Reincarnation is available, but later milestones can improve this life.',
      target: { kind: 'tab', tab: 'prestige' },
    },
    recentDeltas: [
      {
        id: 'reward:1',
        source: 'rewards',
        timestamp: 111,
        tone: 'success',
        label: 'Spoils gained',
        detail: '+300 Gold',
        memoryLine: 'Spoils gained: +300 Gold.',
        rewardSummary: '+300 Gold',
        readinessDelta: { beforeLabel: 'Thin', afterLabel: 'Viable', deltaLabel: '+12 readiness' },
      },
    ],
    debugNotes: ['fixture debug note'],
  };

  return {
    ...base,
    ...overrides,
    milestone: { ...base.milestone, ...overrides.milestone },
    primaryBlocker: { ...base.primaryBlocker, ...overrides.primaryBlocker },
    primaryRoute: { ...base.primaryRoute, ...overrides.primaryRoute },
    readiness: { ...base.readiness, ...overrides.readiness },
    currentCity: overrides.currentCity === undefined ? base.currentCity : overrides.currentCity,
    currentGate: overrides.currentGate === undefined ? base.currentGate : overrides.currentGate,
    safetyNet: overrides.safetyNet === undefined ? base.safetyNet : overrides.safetyNet,
    prestigeHint: overrides.prestigeHint === undefined ? base.prestigeHint : overrides.prestigeHint,
    recentDeltas: overrides.recentDeltas ?? base.recentDeltas,
    debugNotes: overrides.debugNotes ?? base.debugNotes,
  };
}
