import type { UiAssetSpec } from '../types.js';

export const EXISTING_UI_ASSET_REUSE_MAP: UiAssetSpec[] = [
  {
    id: 'ui.reuse.chrome.buttonCorners',
    family: 'chrome',
    subfamily: 'frame',
    status: 'existing-reused',
    logicalName: 'buttoncorners_legacy_frame',
    intendedUse: 'First-pass button frame/chrome corner treatment while dedicated 9-slice arrives.',
    screenFamilies: ['global', 'dense', 'module'],
    textless: true,
    tintable: true,
    nineSliceCandidate: true,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/frames/frame_button_legacy_buttoncorners.png',
    sourcePath: 'src/assets/menus/buttoncorners.png',
    notes: ['Usable as first-pass frame family but needs companion variants and cleaner edges.'],
  },
  {
    id: 'ui.reuse.chrome.scrollFrame',
    family: 'chrome',
    subfamily: 'frame',
    status: 'existing-reused',
    logicalName: 'scroll_legacy_modal_frame',
    intendedUse: 'Legacy scroll texture reused for ritual/modal frame direction.',
    screenFamilies: ['ritual', 'global', 'hero'],
    textless: true,
    tintable: true,
    nineSliceCandidate: true,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/frames/frame_modal_scroll_legacy_scroll.png',
    sourcePath: 'src/assets/menus/scroll.png',
    notes: ['Strong style cue, but requires slice-margin tuning and cleaner variant set later.'],
  },
  {
    id: 'ui.reuse.chrome.barLongRibbon',
    family: 'chrome',
    subfamily: 'ribbon',
    status: 'existing-reused',
    logicalName: 'bar_long_legacy_ribbon',
    intendedUse: 'Long divider/ribbon strip for section separators and progress trims.',
    screenFamilies: ['module', 'dense', 'global'],
    textless: true,
    tintable: true,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/ribbons/ribbon_legacy_bar_long.png',
    sourcePath: 'src/assets/menus/bar_long.png',
    notes: ['Reliable first-pass ribbon; texture density may be high for some dense cards.'],
  },
  {
    id: 'ui.reuse.chrome.barShortRibbon',
    family: 'chrome',
    subfamily: 'ribbon',
    status: 'existing-reused',
    logicalName: 'bar_short_legacy_ribbon',
    intendedUse: 'Short divider/ribbon strip for compact title bars.',
    screenFamilies: ['dense', 'module', 'global'],
    textless: true,
    tintable: true,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/ribbons/ribbon_legacy_bar_short.png',
    sourcePath: 'src/assets/menus/bar_short.png',
    notes: ['Good compact companion to bar_long; keep as interim family only.'],
  },
  {
    id: 'ui.reuse.chrome.blockFancyPlaque',
    family: 'chrome',
    subfamily: 'plaque',
    status: 'existing-reused',
    logicalName: 'block_fancy_legacy_plaque',
    intendedUse: 'Highlight plaque behind key headers and inspector callouts.',
    screenFamilies: ['dense', 'global', 'module'],
    textless: true,
    tintable: true,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/plaques/plaque_legacy_block_fancy.png',
    sourcePath: 'src/assets/menus/block_fancy.png',
    notes: ['Useful plate motif, but not complete as a full plaque scale family.'],
  },
  {
    id: 'ui.reuse.hero.pathBannerHeaven',
    family: 'hero',
    subfamily: 'heartlaw',
    status: 'existing-reused',
    logicalName: 'path_heaven_banner_legacy',
    intendedUse: 'Ritual/path selection banner candidate for Heaven identity.',
    screenFamilies: ['ritual', 'hero', 'global'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/heartlaw/path_banner_heaven_legacy.png',
    sourcePath: 'src/assets/menus/path_heaven 1.png',
    notes: ['Good for path-banner support motif, not strong enough for centerpiece hero kits.'],
  },
  {
    id: 'ui.reuse.hero.pathBannerEarth',
    family: 'hero',
    subfamily: 'heartlaw',
    status: 'existing-reused',
    logicalName: 'path_earth_banner_legacy',
    intendedUse: 'Ritual/path selection banner candidate for Earth identity.',
    screenFamilies: ['ritual', 'hero', 'global'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/heartlaw/path_banner_earth_legacy.png',
    sourcePath: 'src/assets/menus/path_earth 1.png',
    notes: ['Supports path identity quickly; color flexibility is limited.'],
  },
  {
    id: 'ui.reuse.hero.pathBannerMartial',
    family: 'hero',
    subfamily: 'heartlaw',
    status: 'existing-reused',
    logicalName: 'path_martial_banner_legacy',
    intendedUse: 'Ritual/path selection banner candidate for Martial identity.',
    screenFamilies: ['ritual', 'hero', 'global'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/heartlaw/path_banner_martial_legacy.png',
    sourcePath: 'src/assets/menus/path_martial 1.png',
    notes: ['Useful as interim support banner; requires standardized companion kit later.'],
  },
  {
    id: 'ui.reuse.hero.qiLotusClosed',
    family: 'hero',
    subfamily: 'indicator',
    status: 'existing-reused',
    logicalName: 'qi_lotus_closed_indicator',
    intendedUse: 'Closed lotus state indicator in cultivation support motifs.',
    screenFamilies: ['hero', 'module', 'ritual'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/cultivation/indicator_qi_lotus_closed.png',
    sourcePath: 'src/assets/onscreen/qi_lotus_closed.png',
    notes: ['Good for support motif/state indicator, not strong enough for hero centerpiece art.'],
  },
  {
    id: 'ui.reuse.hero.qiLotusOpen',
    family: 'hero',
    subfamily: 'indicator',
    status: 'existing-reused',
    logicalName: 'qi_lotus_open_indicator',
    intendedUse: 'Open lotus state indicator for active cultivation moments.',
    screenFamilies: ['hero', 'module', 'ritual'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/cultivation/indicator_qi_lotus_open.png',
    sourcePath: 'src/assets/onscreen/qi_lotus_open.png',
    notes: ['Readable support motif with existing thematic fit; limited modular layering.'],
  },
  {
    id: 'ui.reuse.hero.qiLotusFull',
    family: 'hero',
    subfamily: 'indicator',
    status: 'existing-reused',
    logicalName: 'qi_lotus_full_indicator',
    intendedUse: 'Full lotus state indicator for high-charge cultivation feedback.',
    screenFamilies: ['hero', 'module', 'ritual'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/cultivation/indicator_qi_lotus_full.png',
    sourcePath: 'src/assets/onscreen/qi_lotus_full.png',
    notes: ['Strong state read; best treated as support motif rather than hero core.'],
  },
  {
    id: 'ui.reuse.chrome.bookSpineHeaven',
    family: 'chrome',
    subfamily: 'utility',
    status: 'existing-reused',
    logicalName: 'book_spine_heaven_legacy',
    intendedUse: 'Book spine accent for manuals/technique shelves and list separators.',
    screenFamilies: ['dense', 'module', 'ritual'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/plaques/book_spine_heaven_legacy.png',
    sourcePath: 'src/assets/ui/book_spines/spine_heaven.png',
    notes: ['Niche but reusable motif for manual stacks and codex styling.'],
  },
  {
    id: 'ui.reuse.chrome.bookSpineEarth',
    family: 'chrome',
    subfamily: 'utility',
    status: 'existing-reused',
    logicalName: 'book_spine_earth_legacy',
    intendedUse: 'Book spine accent for earth/manual categorical grouping.',
    screenFamilies: ['dense', 'module', 'ritual'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/chrome/plaques/book_spine_earth_legacy.png',
    sourcePath: 'src/assets/ui/book_spines/spine_earth.png',
    notes: ['Pairs with other spine variants for taxonomy styling.'],
  },
  {
    id: 'ui.reuse.overlay.cityBase',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'city_base_backdrop_legacy',
    intendedUse: 'World/city backdrop base image.',
    screenFamilies: ['world', 'module'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/world_city_base_legacy.png',
    sourcePath: 'src/assets/background/city.png',
    notes: ['Strong world backdrop candidate with established player familiarity.'],
  },
  {
    id: 'ui.reuse.overlay.cityStateAlchemy',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'citystate_alchemy_overlay_legacy',
    intendedUse: 'City-state overlay for alchemy module context.',
    screenFamilies: ['world', 'module'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/world_citystate_alchemy_legacy.png',
    sourcePath: 'src/assets/background/citystates/city_alchemy.png',
    notes: ['Strong module-specific backdrop candidate.'],
  },
  {
    id: 'ui.reuse.overlay.cityStateForge',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'citystate_forge_overlay_legacy',
    intendedUse: 'City-state overlay for forge module context.',
    screenFamilies: ['world', 'module'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/world_citystate_forge_legacy.png',
    sourcePath: 'src/assets/background/citystates/city_forge.png',
    notes: ['Strong world/module backdrop candidate for forge surfaces.'],
  },
  {
    id: 'ui.reuse.overlay.forgewideShaped',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'forgewide_shaped_backdrop_legacy',
    intendedUse: 'Wide forge backdrop for shaping-focused module presentations.',
    screenFamilies: ['module', 'world'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/module_forgewide_shaped_legacy.png',
    sourcePath: 'src/assets/background/forgewide_shaped.png',
    notes: ['Strong world/module background candidate with clear forge identity.'],
  },
  {
    id: 'ui.reuse.overlay.manualPavilion',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'manual_pavilion_backdrop_legacy',
    intendedUse: 'Manual pavilion background for manual/technique module framing.',
    screenFamilies: ['module', 'world', 'dense'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/module_manual_pavilion_legacy.png',
    sourcePath: 'src/assets/background/manualpavilion.png',
    notes: ['Strong module backdrop candidate, especially for manual-focused surfaces.'],
  },
  {
    id: 'ui.reuse.overlay.techniqueBackdrop',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'technique_backdrop_legacy',
    intendedUse: 'Technique library backdrop candidate.',
    screenFamilies: ['dense', 'module'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/module_technique_backdrop_legacy.png',
    sourcePath: 'src/assets/background/tech.png',
    notes: ['Good first-pass library mood layer; may need lower-contrast variant later.'],
  },
  {
    id: 'ui.reuse.overlay.bountyBoard',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'bountyboard_backdrop_legacy',
    intendedUse: 'Bounty board background candidate for world-module cards.',
    screenFamilies: ['world', 'module'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/module_bountyboard_legacy.png',
    sourcePath: 'src/assets/background/bountyboard.png',
    notes: ['Strong themed backdrop candidate for bounty/adventure panels.'],
  },
  {
    id: 'ui.reuse.overlay.alchemyLabIdle',
    family: 'overlay',
    subfamily: 'background',
    status: 'existing-reused',
    logicalName: 'alchemylab_idle_backdrop_legacy',
    intendedUse: 'Alchemy lab background candidate for workshop modules.',
    screenFamilies: ['module', 'world'],
    textless: true,
    tintable: false,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/overlays/paper/module_alchemylab_idle_legacy.png',
    sourcePath: 'src/assets/background/alchemylab_idle.png',
    notes: ['Strong module backdrop candidate with clear thematic utility.'],
  },
  {
    id: 'ui.reuse.hero.hourglassProgress',
    family: 'hero',
    subfamily: 'indicator',
    status: 'existing-reused',
    logicalName: 'hourglass_progress_indicator_legacy',
    intendedUse: 'Time/progression indicator icon for ritual/module state chips.',
    screenFamilies: ['dense', 'module', 'global'],
    textless: true,
    tintable: true,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/world/indicator_hourglass_progress_legacy.png',
    sourcePath: 'src/assets/icons/hourglass_progress.png',
    notes: ['Good utility indicator and can be tinted for semantic states.'],
  },
  {
    id: 'ui.reuse.hero.hourglassEmpty',
    family: 'hero',
    subfamily: 'indicator',
    status: 'existing-reused',
    logicalName: 'hourglass_empty_indicator_legacy',
    intendedUse: 'Idle/empty timer indicator icon for module cards.',
    screenFamilies: ['dense', 'module', 'global'],
    textless: true,
    tintable: true,
    nineSliceCandidate: false,
    layeredKit: false,
    expectedPath: 'src/assets/ui/heroes/world/indicator_hourglass_empty_legacy.png',
    sourcePath: 'src/assets/icons/hourglass_empty.png',
    notes: ['Pairs with progress variant for simple dual-state timing cues.'],
  },
];
