import type { SoundId } from './soundIds.js';

export type SoundCategory = 'ui' | 'sfx' | 'amb' | 'stg';

export type SoundDef = {
  id: SoundId;
  category: SoundCategory;
  loop?: boolean;
  defaultVolume: number;
};

export const SOUND_CATALOG: Record<SoundId, SoundDef> = {
  'ui_click_primary': { id: 'ui_click_primary', category: 'ui', defaultVolume: 0.6 },
  'ui_click_secondary': { id: 'ui_click_secondary', category: 'ui', defaultVolume: 0.6 },
  'ui_dropdown_open': { id: 'ui_dropdown_open', category: 'ui', defaultVolume: 0.6 },
  'ui_dropdown_select': { id: 'ui_dropdown_select', category: 'ui', defaultVolume: 0.6 },
  'ui_locked': { id: 'ui_locked', category: 'ui', defaultVolume: 0.6 },
  'ui_modal_close': { id: 'ui_modal_close', category: 'ui', defaultVolume: 0.6 },
  'ui_modal_open': { id: 'ui_modal_open', category: 'ui', defaultVolume: 0.6 },
  'ui_tab_switch': { id: 'ui_tab_switch', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_critical': { id: 'ui_toast_critical', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_info': { id: 'ui_toast_info', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_success': { id: 'ui_toast_success', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_warning': { id: 'ui_toast_warning', category: 'ui', defaultVolume: 0.6 },
  'ui_building_enter': { id: 'ui_building_enter', category: 'ui', defaultVolume: 0.6 },
  'amb_building_manual_pavilion_loop': {
    id: 'amb_building_manual_pavilion_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'ui_pavilion_refresh_confirm': { id: 'ui_pavilion_refresh_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_stock_roll': { id: 'ui_pavilion_stock_roll', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_stock_reveal': { id: 'ui_pavilion_stock_reveal', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_refresh_denied': { id: 'ui_pavilion_refresh_denied', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_click': { id: 'ui_pavilion_buy_click', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_success': { id: 'ui_pavilion_buy_success', category: 'ui', defaultVolume: 0.6 },
  'ui_item_pickup': { id: 'ui_item_pickup', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_fail': { id: 'ui_pavilion_buy_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_pity_increment': { id: 'ui_pavilion_pity_increment', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_pity_major': { id: 'ui_pavilion_pity_major', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_guarantee_trigger': { id: 'ui_pavilion_guarantee_trigger', category: 'ui', defaultVolume: 0.6 },
  'ui_satchel_open': { id: 'ui_satchel_open', category: 'ui', defaultVolume: 0.6 },
  'ui_satchel_close': { id: 'ui_satchel_close', category: 'ui', defaultVolume: 0.6 },
  'sfx_study_start': { id: 'sfx_study_start', category: 'sfx', defaultVolume: 0.8 },
  'ui_study_timer_start': { id: 'ui_study_timer_start', category: 'ui', defaultVolume: 0.6 },
  'ui_study_timer_complete': { id: 'ui_study_timer_complete', category: 'ui', defaultVolume: 0.6 },
  'stg_technique_learned': { id: 'stg_technique_learned', category: 'stg', defaultVolume: 0.85 },
  'ui_learned_popup_open': { id: 'ui_learned_popup_open', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_prompt_appear': { id: 'ui_focus_prompt_appear', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_success': { id: 'ui_focus_success', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_fail': { id: 'ui_focus_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_equip_now_click': { id: 'ui_equip_now_click', category: 'ui', defaultVolume: 0.6 },
  'ui_techlib_open': { id: 'ui_techlib_open', category: 'ui', defaultVolume: 0.6 },
  'ui_techlib_close': { id: 'ui_techlib_close', category: 'ui', defaultVolume: 0.6 },
  'ui_loadout_switch': { id: 'ui_loadout_switch', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_select': { id: 'ui_slot_select', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_locked': { id: 'ui_slot_locked', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_unlock': { id: 'ui_slot_unlock', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_equip': { id: 'ui_tech_equip', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_swap': { id: 'ui_tech_swap', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_unequip': { id: 'ui_tech_unequip', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_open': { id: 'ui_rank_upgrade_open', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_confirm': { id: 'ui_rank_upgrade_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_success': { id: 'ui_rank_upgrade_success', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_fail': { id: 'ui_rank_upgrade_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_open': { id: 'ui_trait_reroll_open', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_spin': { id: 'ui_trait_reroll_spin', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_confirm': { id: 'ui_trait_reroll_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_result': { id: 'ui_trait_reroll_result', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_socket_open': { id: 'ui_rune_socket_open', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_insert': { id: 'ui_rune_insert', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_remove': { id: 'ui_rune_remove', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_upgrade': { id: 'ui_rune_upgrade', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_craft_success': { id: 'ui_rune_craft_success', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_craft_fail': { id: 'ui_rune_craft_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_gain_small': { id: 'ui_currency_gain_small', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_gain_large': { id: 'ui_currency_gain_large', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_spend': { id: 'ui_currency_spend', category: 'ui', defaultVolume: 0.6 },
  'sfx_fragment_bundle': { id: 'sfx_fragment_bundle', category: 'sfx', defaultVolume: 0.8 },
  'ui_apothecary_open': { id: 'ui_apothecary_open', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_close': { id: 'ui_apothecary_close', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_item_select': { id: 'ui_apothecary_item_select', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_buy_success': { id: 'ui_apothecary_buy_success', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_buy_fail': { id: 'ui_apothecary_buy_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_daily_limit_hit': { id: 'ui_apothecary_daily_limit_hit', category: 'ui', defaultVolume: 0.6 },
  'ui_apothecary_bundle_buy': { id: 'ui_apothecary_bundle_buy', category: 'ui', defaultVolume: 0.6 },
  'ui_pouch_open': { id: 'ui_pouch_open', category: 'ui', defaultVolume: 0.6 },
  'ui_pouch_close': { id: 'ui_pouch_close', category: 'ui', defaultVolume: 0.6 },
  'ui_pouch_slot_select': { id: 'ui_pouch_slot_select', category: 'ui', defaultVolume: 0.6 },
  'ui_pouch_equip_item': { id: 'ui_pouch_equip_item', category: 'ui', defaultVolume: 0.6 },
  'ui_pouch_unequip_item': { id: 'ui_pouch_unequip_item', category: 'ui', defaultVolume: 0.6 },
  'sfx_pouch_auto_use_trigger': { id: 'sfx_pouch_auto_use_trigger', category: 'sfx', defaultVolume: 0.8 },
  'sfx_pouch_out_of_charges': { id: 'sfx_pouch_out_of_charges', category: 'sfx', defaultVolume: 0.8 },
  'sfx_pouch_low_charges_warning': { id: 'sfx_pouch_low_charges_warning', category: 'sfx', defaultVolume: 0.8 },
  'ui_crafting_open': { id: 'ui_crafting_open', category: 'ui', defaultVolume: 0.6 },
  'ui_crafting_close': { id: 'ui_crafting_close', category: 'ui', defaultVolume: 0.6 },
  'ui_recipe_select': { id: 'ui_recipe_select', category: 'ui', defaultVolume: 0.6 },
  'ui_recipe_locked': { id: 'ui_recipe_locked', category: 'ui', defaultVolume: 0.6 },
  'ui_recipe_unlock': { id: 'ui_recipe_unlock', category: 'ui', defaultVolume: 0.6 },
  'ui_mode_idle_select': { id: 'ui_mode_idle_select', category: 'ui', defaultVolume: 0.6 },
  'ui_mode_assisted_select': { id: 'ui_mode_assisted_select', category: 'ui', defaultVolume: 0.6 },
  'ui_mode_handson_select': { id: 'ui_mode_handson_select', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_add': { id: 'ui_queue_add', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_remove': { id: 'ui_queue_remove', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_reorder': { id: 'ui_queue_reorder', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_start': { id: 'ui_queue_start', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_pause': { id: 'ui_queue_pause', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_resume': { id: 'ui_queue_resume', category: 'ui', defaultVolume: 0.6 },
  'ui_queue_complete': { id: 'ui_queue_complete', category: 'ui', defaultVolume: 0.6 },
  'ui_assist_prompt_appear': { id: 'ui_assist_prompt_appear', category: 'ui', defaultVolume: 0.6 },
  'ui_assist_prompt_success': { id: 'ui_assist_prompt_success', category: 'ui', defaultVolume: 0.6 },
  'ui_assist_prompt_fail': { id: 'ui_assist_prompt_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_assist_prompt_timeout': { id: 'ui_assist_prompt_timeout', category: 'ui', defaultVolume: 0.6 },
  'amb_city_hub_day_loop': { id: 'amb_city_hub_day_loop', category: 'amb', defaultVolume: 0.35, loop: true },
  'amb_building_apothecary_loop': {
    id: 'amb_building_apothecary_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_building_alchemy_hall_loop': {
    id: 'amb_building_alchemy_hall_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_building_forge_loop': { id: 'amb_building_forge_loop', category: 'amb', defaultVolume: 0.35, loop: true },
  'amb_building_talisman_studio_loop': {
    id: 'amb_building_talisman_studio_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_building_bounty_board_loop': {
    id: 'amb_building_bounty_board_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_building_expedition_board_loop': {
    id: 'amb_building_expedition_board_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_building_meditation_hall_loop': {
    id: 'amb_building_meditation_hall_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'amb_outskirts_loop': { id: 'amb_outskirts_loop', category: 'amb', defaultVolume: 0.35, loop: true },
  'amb_trial_loop': { id: 'amb_trial_loop', category: 'amb', defaultVolume: 0.35, loop: true },
  'amb_ruins_loop': { id: 'amb_ruins_loop', category: 'amb', defaultVolume: 0.35, loop: true },
  'sfx_alchemy_flame_ignite': { id: 'sfx_alchemy_flame_ignite', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_flame_adjust': { id: 'sfx_alchemy_flame_adjust', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_flame_surge': { id: 'sfx_alchemy_flame_surge', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_flame_stable': { id: 'sfx_alchemy_flame_stable', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_ingredient_add': { id: 'sfx_alchemy_ingredient_add', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_seal': { id: 'sfx_alchemy_seal', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_pressure_release': { id: 'sfx_alchemy_pressure_release', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_step_perfect': { id: 'sfx_alchemy_step_perfect', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_step_good': { id: 'sfx_alchemy_step_good', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_step_miss': { id: 'sfx_alchemy_step_miss', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_result_crude': { id: 'sfx_alchemy_result_crude', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_result_perfect': { id: 'sfx_alchemy_result_perfect', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_byproduct_gain': { id: 'sfx_alchemy_byproduct_gain', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_mastery_gain': { id: 'sfx_alchemy_mastery_gain', category: 'sfx', defaultVolume: 0.8 },
  'sfx_alchemy_mastery_milestone': { id: 'sfx_alchemy_mastery_milestone', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_furnace_ignite': { id: 'sfx_forge_furnace_ignite', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_bellows_pump': { id: 'sfx_forge_bellows_pump', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_metal_heat': { id: 'sfx_forge_metal_heat', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_hammer_light': { id: 'sfx_forge_hammer_light', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_hammer_heavy': { id: 'sfx_forge_hammer_heavy', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_sparks_burst': { id: 'sfx_forge_sparks_burst', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_quench': { id: 'sfx_forge_quench', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_temper': { id: 'sfx_forge_temper', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_grind': { id: 'sfx_forge_grind', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_refine_success': { id: 'sfx_forge_refine_success', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_refine_fail': { id: 'sfx_forge_refine_fail', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_temper_proc': { id: 'sfx_forge_temper_proc', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_temper_no_proc': { id: 'sfx_forge_temper_no_proc', category: 'sfx', defaultVolume: 0.8 },
  'ui_forge_delta_open': { id: 'ui_forge_delta_open', category: 'ui', defaultVolume: 0.6 },
  'ui_forge_delta_close': { id: 'ui_forge_delta_close', category: 'ui', defaultVolume: 0.6 },
  'sfx_forge_rune_engrave': { id: 'sfx_forge_rune_engrave', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_rune_fuse': { id: 'sfx_forge_rune_fuse', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_rune_craft_success': { id: 'sfx_forge_rune_craft_success', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_rune_craft_fail': { id: 'sfx_forge_rune_craft_fail', category: 'sfx', defaultVolume: 0.8 },
  'sfx_forge_rune_dust_gain': { id: 'sfx_forge_rune_dust_gain', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_paper_pickup': { id: 'sfx_talisman_paper_pickup', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_brush_stroke': { id: 'sfx_talisman_brush_stroke', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_ink_dip': { id: 'sfx_talisman_ink_dip', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_seal_stamp': { id: 'sfx_talisman_seal_stamp', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_craft_success': { id: 'sfx_talisman_craft_success', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_craft_fail': { id: 'sfx_talisman_craft_fail', category: 'sfx', defaultVolume: 0.8 },
  'ui_talisman_equip': { id: 'ui_talisman_equip', category: 'ui', defaultVolume: 0.6 },
  'ui_talisman_unequip': { id: 'ui_talisman_unequip', category: 'ui', defaultVolume: 0.6 },
  'sfx_talisman_trigger': { id: 'sfx_talisman_trigger', category: 'sfx', defaultVolume: 0.8 },
  'sfx_talisman_break': { id: 'sfx_talisman_break', category: 'sfx', defaultVolume: 0.8 },
};
