import type { SoundId } from './soundIds';

export type SoundCategory = 'ui' | 'sfx' | 'amb' | 'stg';

export type SoundDef = {
  id: SoundId;
  category: SoundCategory;
  loop?: boolean;
  defaultVolume: number;
};

export const SOUND_CATALOG: Record<SoundId, SoundDef> = {
  'ui_click_primary': { id: 'ui_click_primary', category: 'ui', defaultVolume: 0.6 },
  'ui_click_secondary': { id: 'ui_click_secondary', category: 'ui', defaultVolume: 0.6 },
  'ui_dropdown_open': { id: 'ui_dropdown_open', category: 'ui', defaultVolume: 0.6 },
  'ui_dropdown_select': { id: 'ui_dropdown_select', category: 'ui', defaultVolume: 0.6 },
  'ui_locked': { id: 'ui_locked', category: 'ui', defaultVolume: 0.6 },
  'ui_modal_close': { id: 'ui_modal_close', category: 'ui', defaultVolume: 0.6 },
  'ui_modal_open': { id: 'ui_modal_open', category: 'ui', defaultVolume: 0.6 },
  'ui_tab_switch': { id: 'ui_tab_switch', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_critical': { id: 'ui_toast_critical', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_info': { id: 'ui_toast_info', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_success': { id: 'ui_toast_success', category: 'ui', defaultVolume: 0.6 },
  'ui_toast_warning': { id: 'ui_toast_warning', category: 'ui', defaultVolume: 0.6 },
  'ui_building_enter': { id: 'ui_building_enter', category: 'ui', defaultVolume: 0.6 },
  'amb_building_manual_pavilion_loop': {
    id: 'amb_building_manual_pavilion_loop',
    category: 'amb',
    defaultVolume: 0.35,
    loop: true,
  },
  'ui_pavilion_refresh_confirm': { id: 'ui_pavilion_refresh_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_stock_roll': { id: 'ui_pavilion_stock_roll', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_stock_reveal': { id: 'ui_pavilion_stock_reveal', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_refresh_denied': { id: 'ui_pavilion_refresh_denied', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_click': { id: 'ui_pavilion_buy_click', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_success': { id: 'ui_pavilion_buy_success', category: 'ui', defaultVolume: 0.6 },
  'ui_item_pickup': { id: 'ui_item_pickup', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_buy_fail': { id: 'ui_pavilion_buy_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_pity_increment': { id: 'ui_pavilion_pity_increment', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_pity_major': { id: 'ui_pavilion_pity_major', category: 'ui', defaultVolume: 0.6 },
  'ui_pavilion_guarantee_trigger': { id: 'ui_pavilion_guarantee_trigger', category: 'ui', defaultVolume: 0.6 },
  'ui_satchel_open': { id: 'ui_satchel_open', category: 'ui', defaultVolume: 0.6 },
  'ui_satchel_close': { id: 'ui_satchel_close', category: 'ui', defaultVolume: 0.6 },
  'sfx_study_start': { id: 'sfx_study_start', category: 'sfx', defaultVolume: 0.8 },
  'ui_study_timer_start': { id: 'ui_study_timer_start', category: 'ui', defaultVolume: 0.6 },
  'ui_study_timer_complete': { id: 'ui_study_timer_complete', category: 'ui', defaultVolume: 0.6 },
  'stg_technique_learned': { id: 'stg_technique_learned', category: 'stg', defaultVolume: 0.85 },
  'ui_learned_popup_open': { id: 'ui_learned_popup_open', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_prompt_appear': { id: 'ui_focus_prompt_appear', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_success': { id: 'ui_focus_success', category: 'ui', defaultVolume: 0.6 },
  'ui_focus_fail': { id: 'ui_focus_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_equip_now_click': { id: 'ui_equip_now_click', category: 'ui', defaultVolume: 0.6 },
  'ui_techlib_open': { id: 'ui_techlib_open', category: 'ui', defaultVolume: 0.6 },
  'ui_techlib_close': { id: 'ui_techlib_close', category: 'ui', defaultVolume: 0.6 },
  'ui_loadout_switch': { id: 'ui_loadout_switch', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_select': { id: 'ui_slot_select', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_locked': { id: 'ui_slot_locked', category: 'ui', defaultVolume: 0.6 },
  'ui_slot_unlock': { id: 'ui_slot_unlock', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_equip': { id: 'ui_tech_equip', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_swap': { id: 'ui_tech_swap', category: 'ui', defaultVolume: 0.6 },
  'ui_tech_unequip': { id: 'ui_tech_unequip', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_open': { id: 'ui_rank_upgrade_open', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_confirm': { id: 'ui_rank_upgrade_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_success': { id: 'ui_rank_upgrade_success', category: 'ui', defaultVolume: 0.6 },
  'ui_rank_upgrade_fail': { id: 'ui_rank_upgrade_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_open': { id: 'ui_trait_reroll_open', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_spin': { id: 'ui_trait_reroll_spin', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_confirm': { id: 'ui_trait_reroll_confirm', category: 'ui', defaultVolume: 0.6 },
  'ui_trait_reroll_result': { id: 'ui_trait_reroll_result', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_socket_open': { id: 'ui_rune_socket_open', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_insert': { id: 'ui_rune_insert', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_remove': { id: 'ui_rune_remove', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_upgrade': { id: 'ui_rune_upgrade', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_craft_success': { id: 'ui_rune_craft_success', category: 'ui', defaultVolume: 0.6 },
  'ui_rune_craft_fail': { id: 'ui_rune_craft_fail', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_gain_small': { id: 'ui_currency_gain_small', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_gain_large': { id: 'ui_currency_gain_large', category: 'ui', defaultVolume: 0.6 },
  'ui_currency_spend': { id: 'ui_currency_spend', category: 'ui', defaultVolume: 0.6 },
  'sfx_fragment_bundle': { id: 'sfx_fragment_bundle', category: 'sfx', defaultVolume: 0.8 },
};
