import type { FxFoundationChecklistEntry } from './types.js';

export const FX_FOUNDATION_COMPLIANCE_CHECKLIST: FxFoundationChecklistEntry[] = [
  {
    id: 'dom-readable-ui',
    category: 'readability',
    title: 'Readable UI stays in DOM',
    rule: 'Readable text, forms, counters, lists, and checklists stay in DOM.',
    whyItMatters: 'Readability, accessibility tooling, and interaction reliability depend on DOM-native text surfaces.',
  },
  {
    id: 'no-pixi-text',
    category: 'readability',
    title: 'No Pixi gameplay text',
    rule: 'No readable gameplay text is rendered through Pixi.',
    whyItMatters: 'Pixi text introduces readability, localization, and accessibility drift from the core UI stack.',
  },
  {
    id: 'provider-store-boundary',
    category: 'ownership',
    title: 'Provider/store boundary',
    rule: 'FxQualityProvider remains store-agnostic.',
    whyItMatters: 'Keeping provider contracts pure prevents hidden coupling and makes diagnostics/test mounting predictable.',
  },
  {
    id: 'single-app-provider',
    category: 'integration',
    title: 'Single provider ownership',
    rule: 'Do not mount a second provider outside the app bridge.',
    whyItMatters: 'Multiple providers create conflicting quality truth and hard-to-debug scene behavior differences.',
  },
  {
    id: 'use-primitives-first',
    category: 'integration',
    title: 'Primitive-first screen composition',
    rule: 'Later screens should prefer ScenicBackdropMount, AmbientUnderlayMount, HeroFxSlot, and SafeDomOverlaySlot before raw stage composition.',
    whyItMatters: 'Shared primitives keep fallback, layering, and reduced-motion handling consistent across packets.',
  },
  {
    id: 'local-before-global',
    category: 'layering',
    title: 'Local stages first',
    rule: 'Prefer local stage mounts; use global portal only when truly justified.',
    whyItMatters: 'Local containment reduces global layer collisions and keeps scene ownership traceable.',
  },
  {
    id: 'quality-floor-respected',
    category: 'quality',
    title: 'Quality floors respected',
    rule: 'Any mounted FX must honor quality floor and resolved quality.',
    whyItMatters: 'Ignoring quality contracts breaks low-end stability and user intent from settings.',
  },
  {
    id: 'reduced-motion-respected',
    category: 'quality',
    title: 'Reduced-motion respected',
    rule: 'Reduced motion must clamp or replace animated output.',
    whyItMatters: 'Motion accessibility depends on strict clamping behavior and deterministic fallback paths.',
  },
  {
    id: 'static-fallback-defined',
    category: 'fallback',
    title: 'Static fallback defined',
    rule: 'If a screen relies on animated atmosphere for readability or composition, low/static/reduced-motion fallback behavior must be defined.',
    whyItMatters: 'Static/off paths must remain coherent so key screen information does not disappear when animation is unavailable.',
  },
  {
    id: 'no-new-global-z',
    category: 'layering',
    title: 'No ad hoc global z-bands',
    rule: 'No packet may invent new app-global z-index bands outside the layer contract.',
    whyItMatters: 'Uncoordinated z-bands cause modal/overlay regressions and hidden interaction bugs.',
  },
  {
    id: 'screen-no-store-coupling-inside-fx',
    category: 'ownership',
    title: 'No gameplay store coupling in fx/',
    rule: 'Files under src/ui/fx/** must not import gameplay stores.',
    whyItMatters: 'Foundation code must stay reusable and deterministic without direct game-state ownership.',
  },
  {
    id: 'content-overlay-readable',
    category: 'readability',
    title: 'Overlay readability and interaction preserved',
    rule: 'Readable overlay content must remain above local hero/underlay FX and must stay interactive where intended.',
    whyItMatters: 'Layering regressions can silently break click targets and hide mission-critical player information.',
  },
  {
    id: 'diagnostics-attrs-present',
    category: 'integration',
    title: 'Diagnostics attributes present',
    rule: 'Foundation mounts should stamp stable diagnostics attributes for stage kind, mount kind, and mount mode.',
    whyItMatters: 'Consistent QA snapshots require durable, packet-stable runtime markers.',
  },
  {
    id: 'fallback-warnings-reviewed',
    category: 'fallback',
    title: 'Fallback warnings reviewed',
    rule: 'New scenic packets should review diagnostics warnings and explain any intentional mixed/static/off states.',
    whyItMatters: 'Warnings prevent silent regressions where animated and static paths drift apart.',
  },
];
