import type { ItemDefinition } from '../types';

export const ITEMS_DATABASE: Record<string, ItemDefinition> = {
  // ===== WEAPONS =====
  rusty_sword: {
    id: 'rusty_sword',
    name: 'Rusty Sword',
    description: 'An old, worn blade. Better than nothing.',
    type: 'weapon',
    rarity: 'common',
    level: 1,
    stats: { atk: '10' },
    value: '50',
    stackable: false,
    maxStack: 1,
  },
  basic_sword: {
    id: 'basic_sword',
    name: 'Iron Sword',
    description: 'A simple iron sword for beginners.',
    type: 'weapon',
    rarity: 'common',
    level: 1,
    stats: { atk: '25', crit: 2 },
    value: '100',
    stackable: false,
    maxStack: 1,
  },
  steel_blade: {
    id: 'steel_blade',
    name: 'Steel Blade',
    description: 'A well-crafted steel sword.',
    type: 'weapon',
    rarity: 'uncommon',
    level: 5,
    stats: { atk: '50', crit: 5, critDmg: 10 },
    value: '500',
    stackable: false,
    maxStack: 1,
  },
  spirit_blade: {
    id: 'spirit_blade',
    name: 'Spirit Blade',
    description: 'A blade infused with spiritual energy.',
    type: 'weapon',
    rarity: 'rare',
    level: 10,
    stats: { atk: '100', crit: 10, critDmg: 25 },
    value: '2000',
    stackable: false,
    maxStack: 1,
  },
  dragon_fang: {
    id: 'dragon_fang',
    name: 'Dragon Fang Sword',
    description: 'Forged from the fang of an ancient dragon.',
    type: 'weapon',
    rarity: 'epic',
    level: 15,
    stats: { atk: '250', crit: 15, critDmg: 50 },
    value: '10000',
    stackable: false,
    maxStack: 1,
  },
  immortal_blade: {
    id: 'immortal_blade',
    name: 'Immortal\'s Edge',
    description: 'A legendary blade wielded by immortals.',
    type: 'weapon',
    rarity: 'legendary',
    level: 20,
    stats: { atk: '500', crit: 25, critDmg: 100, dodge: 5 },
    value: '50000',
    stackable: false,
    maxStack: 1,
  },

  // ===== ACCESSORIES =====
  worn_talisman: {
    id: 'worn_talisman',
    name: 'Worn Talisman',
    description: 'An old protective charm.',
    type: 'accessory',
    rarity: 'common',
    level: 1,
    stats: { hp: '50', def: '5' },
    value: '50',
    stackable: false,
    maxStack: 1,
  },
  jade_pendant: {
    id: 'jade_pendant',
    name: 'Jade Pendant',
    description: 'A beautiful jade pendant that enhances cultivation.',
    type: 'accessory',
    rarity: 'uncommon',
    level: 5,
    stats: { hp: '150', def: '15', qiGain: 10 },
    value: '400',
    stackable: false,
    maxStack: 1,
  },
  spirit_ring: {
    id: 'spirit_ring',
    name: 'Spirit Ring',
    description: 'A ring that channels spiritual power.',
    type: 'accessory',
    rarity: 'rare',
    level: 10,
    stats: { hp: '300', def: '30', qiGain: 20, dodge: 3 },
    value: '1500',
    stackable: false,
    maxStack: 1,
  },
  phoenix_feather: {
    id: 'phoenix_feather',
    name: 'Phoenix Feather Amulet',
    description: 'Contains the essence of a phoenix.',
    type: 'accessory',
    rarity: 'epic',
    level: 15,
    stats: { hp: '600', def: '60', qiGain: 40, dodge: 8 },
    value: '8000',
    stackable: false,
    maxStack: 1,
  },
  heavenly_jade: {
    id: 'heavenly_jade',
    name: 'Heavenly Jade Seal',
    description: 'A jade seal blessed by the heavens.',
    type: 'accessory',
    rarity: 'legendary',
    level: 20,
    stats: { hp: '1200', def: '120', qiGain: 80, dodge: 15, crit: 10 },
    value: '40000',
    stackable: false,
    maxStack: 1,
  },

  // ===== CONSUMABLES =====
  health_pill: {
    id: 'health_pill',
    name: 'Health Pill',
    description: 'Restores 50% of maximum HP.',
    type: 'consumable',
    rarity: 'common',
    level: 1,
    consumable: { healPercent: 50 },
    value: '25',
    stackable: true,
    maxStack: 99,
  },
  greater_health_pill: {
    id: 'greater_health_pill',
    name: 'Greater Health Pill',
    description: 'Restores 100% of maximum HP.',
    type: 'consumable',
    rarity: 'uncommon',
    level: 5,
    consumable: { healPercent: 100 },
    value: '100',
    stackable: true,
    maxStack: 99,
  },
  supreme_health_pill: {
    id: 'supreme_health_pill',
    name: 'Supreme Health Pill',
    description: 'Fully restores HP and grants temporary vitality.',
    type: 'consumable',
    rarity: 'rare',
    level: 10,
    consumable: { healPercent: 100, buffDuration: 30, buffStats: { def: 20 } },
    value: '500',
    stackable: true,
    maxStack: 99,
  },

  // ===== BREAKTHROUGH ITEMS =====
  foundation_pill: {
    id: 'foundation_pill',
    name: 'Foundation Pill',
    description: 'Required to breakthrough from Qi Refining to Foundation Establishment.',
    type: 'material',
    rarity: 'rare',
    level: 5,
    value: '0',
    stackable: true,
    maxStack: 99,
  },
  core_catalyst: {
    id: 'core_catalyst',
    name: 'Core Catalyst',
    description: 'Required to breakthrough from Foundation to Core Formation.',
    type: 'material',
    rarity: 'epic',
    level: 10,
    value: '0',
    stackable: true,
    maxStack: 99,
  },
  core_stabilizer: {
    id: 'core_stabilizer',
    name: 'Core Stabilizer',
    description: 'Required to breakthrough from Core Formation to Nascent Soul.',
    type: 'material',
    rarity: 'epic',
    level: 15,
    value: '0',
    stackable: true,
    maxStack: 99,
  },
  soul_condensate: {
    id: 'soul_condensate',
    name: 'Soul Condensate',
    description: 'Required to breakthrough from Nascent Soul to Soul Formation.',
    type: 'material',
    rarity: 'legendary',
    level: 20,
    value: '0',
    stackable: true,
    maxStack: 99,
  },

  // ===== MATERIALS =====
  spirit_stone: {
    id: 'spirit_stone',
    name: 'Spirit Stone',
    description: 'A stone containing concentrated spiritual energy. Used for crafting.',
    type: 'material',
    rarity: 'common',
    level: 1,
    value: '10',
    stackable: true,
    maxStack: 999,
  },
  qi_crystal: {
    id: 'qi_crystal',
    name: 'Qi Crystal',
    description: 'A crystallized form of pure Qi. Valuable crafting material.',
    type: 'material',
    rarity: 'uncommon',
    level: 5,
    value: '50',
    stackable: true,
    maxStack: 999,
  },
  dragon_scale: {
    id: 'dragon_scale',
    name: 'Dragon Scale',
    description: 'A scale from a mighty dragon. Extremely rare.',
    type: 'material',
    rarity: 'epic',
    level: 15,
    value: '5000',
    stackable: true,
    maxStack: 99,
  },
  immortal_essence: {
    id: 'immortal_essence',
    name: 'Immortal Essence',
    description: 'The essence of immortality itself. Priceless.',
    type: 'material',
    rarity: 'legendary',
    level: 20,
    value: '100000',
    stackable: true,
    maxStack: 10,
  },
  boar_hide: {
    id: 'boar_hide',
    name: 'Boar Hide',
    description: 'Tough hide used in basic armor crafting.',
    type: 'material',
    rarity: 'common',
    level: 1,
    value: '8',
    stackable: true,
    maxStack: 999,
  },
  raw_meat: {
    id: 'raw_meat',
    name: 'Raw Meat',
    description: 'Fresh hunt remains with modest market value.',
    type: 'material',
    rarity: 'common',
    level: 1,
    value: '6',
    stackable: true,
    maxStack: 999,
  },
  rabbit_pelt: {
    id: 'rabbit_pelt',
    name: 'Rabbit Pelt',
    description: 'Soft pelt favored by novice crafters.',
    type: 'material',
    rarity: 'common',
    level: 1,
    value: '7',
    stackable: true,
    maxStack: 999,
  },
  lucky_foot: {
    id: 'lucky_foot',
    name: 'Lucky Foot',
    description: 'A charm-like trinket with minor trade value.',
    type: 'material',
    rarity: 'uncommon',
    level: 2,
    value: '20',
    stackable: true,
    maxStack: 999,
  },
  wolf_fang: {
    id: 'wolf_fang',
    name: 'Wolf Fang',
    description: 'A sharp fang often used for weapon inlays.',
    type: 'material',
    rarity: 'uncommon',
    level: 4,
    value: '26',
    stackable: true,
    maxStack: 999,
  },
  wolf_pelt: {
    id: 'wolf_pelt',
    name: 'Wolf Pelt',
    description: 'Dense fur from a wild wolf.',
    type: 'material',
    rarity: 'common',
    level: 4,
    value: '16',
    stackable: true,
    maxStack: 999,
  },
  spider_silk: {
    id: 'spider_silk',
    name: 'Spider Silk',
    description: 'A flexible thread prized by artisans.',
    type: 'material',
    rarity: 'uncommon',
    level: 6,
    value: '35',
    stackable: true,
    maxStack: 999,
  },
  venom_sac: {
    id: 'venom_sac',
    name: 'Venom Sac',
    description: 'A risky but valuable alchemy ingredient.',
    type: 'material',
    rarity: 'rare',
    level: 6,
    value: '80',
    stackable: true,
    maxStack: 999,
  },
  stone_core: {
    id: 'stone_core',
    name: 'Stone Core',
    description: 'Condensed essence from a stone construct.',
    type: 'material',
    rarity: 'rare',
    level: 8,
    value: '95',
    stackable: true,
    maxStack: 999,
  },
  iron_ore: {
    id: 'iron_ore',
    name: 'Iron Ore',
    description: 'Refinable ore from deep caverns.',
    type: 'material',
    rarity: 'common',
    level: 8,
    value: '14',
    stackable: true,
    maxStack: 999,
  },
  bat_wing: {
    id: 'bat_wing',
    name: 'Bat Wing',
    description: 'A membrane used in spiritual reagents.',
    type: 'material',
    rarity: 'uncommon',
    level: 7,
    value: '30',
    stackable: true,
    maxStack: 999,
  },
  spirit_essence: {
    id: 'spirit_essence',
    name: 'Spirit Essence',
    description: 'Concentrated spirit residue from cave denizens.',
    type: 'material',
    rarity: 'rare',
    level: 7,
    value: '120',
    stackable: true,
    maxStack: 999,
  },
  tiger_claw: {
    id: 'tiger_claw',
    name: 'Tiger Claw',
    description: 'A brutal claw radiating feral qi.',
    type: 'material',
    rarity: 'rare',
    level: 12,
    value: '180',
    stackable: true,
    maxStack: 999,
  },
  beast_core: {
    id: 'beast_core',
    name: 'Beast Core',
    description: 'A high-density core from mountain apex predators.',
    type: 'material',
    rarity: 'epic',
    level: 12,
    value: '450',
    stackable: true,
    maxStack: 999,
  },
  frost_scale: {
    id: 'frost_scale',
    name: 'Frost Scale',
    description: 'A chilled scale from ancient serpents.',
    type: 'material',
    rarity: 'rare',
    level: 15,
    value: '250',
    stackable: true,
    maxStack: 999,
  },
  celestial_jade: {
    id: 'celestial_jade',
    name: 'Celestial Jade',
    description: 'A jade fragment infused with astral energy.',
    type: 'material',
    rarity: 'epic',
    level: 15,
    value: '700',
    stackable: true,
    maxStack: 999,
  },

  // ===== TREASURE ITEMS =====
  gold_coin: {
    id: 'gold_coin',
    name: 'Gold Coin',
    description: 'Currency used throughout the cultivation world.',
    type: 'treasure',
    rarity: 'common',
    level: 1,
    value: '1',
    stackable: true,
    maxStack: 999999,
  },
};
