import type { UiAssetManifest } from '../types.js';

export const OVERLAY_UI_ASSET_MANIFEST: UiAssetManifest = {
  family: 'overlay',
  assets: [
    {
      id: 'ui.overlay.paperGrainSoft',
      family: 'overlay',
      subfamily: 'paper',
      status: 'planned-missing',
      logicalName: 'paper_grain_soft',
      intendedUse: 'Soft paper grain overlay for base scene texture.',
      screenFamilies: ['global', 'world', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/paper/paper_grain_soft.png',
      notes: ['General-purpose paper texture; keep contrast low for readability.'],
    },
    {
      id: 'ui.overlay.paperGrainHeavy',
      family: 'overlay',
      subfamily: 'paper',
      status: 'planned-missing',
      logicalName: 'paper_grain_heavy',
      intendedUse: 'Heavier paper grain for modal/inspector focus layers.',
      screenFamilies: ['dense', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/paper/paper_grain_heavy.png',
      notes: ['Use selectively to avoid flattening hierarchy.'],
    },
    {
      id: 'ui.overlay.fogEdgeSoft',
      family: 'overlay',
      subfamily: 'mask',
      status: 'planned-missing',
      logicalName: 'fog_edge_soft',
      intendedUse: 'Soft fog edge mask for scenic depth falloff.',
      screenFamilies: ['hero', 'world', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/masks/fog_edge_soft.png',
      notes: ['Works as gentle edge fade for atmosphere staging.'],
    },
    {
      id: 'ui.overlay.vignetteSoft',
      family: 'overlay',
      subfamily: 'mask',
      status: 'planned-missing',
      logicalName: 'vignette_soft',
      intendedUse: 'Soft vignette for focus framing and edge darkening.',
      screenFamilies: ['global', 'hero', 'world'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/masks/vignette_soft.png',
      notes: ['Use for depth, not as a heavy readability crutch.'],
    },
    {
      id: 'ui.overlay.tornEdgeMaskSoft',
      family: 'overlay',
      subfamily: 'mask',
      status: 'planned-missing',
      logicalName: 'torn_edge_mask_soft',
      intendedUse: 'Soft torn edge mask for parchment framing.',
      screenFamilies: ['ritual', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/masks/torn_edge_mask_soft.png',
      notes: ['Should remain text-free and reusable across layouts.'],
    },
    {
      id: 'ui.overlay.parchmentWashRadial',
      family: 'overlay',
      subfamily: 'paper',
      status: 'planned-missing',
      logicalName: 'parchment_wash_radial',
      intendedUse: 'Radial parchment wash for hero/module focal regions.',
      screenFamilies: ['hero', 'module', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/overlays/paper/parchment_wash_radial.png',
      notes: ['Supports focal contrast without introducing text or iconography.'],
    },
  ],
};
