import type { UiAssetManifest } from '../types.js';

export const CHROME_UI_ASSET_MANIFEST: UiAssetManifest = {
  family: 'chrome',
  assets: [
    {
      id: 'ui.chrome.frameCardThin9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_card_thin_9slice',
      intendedUse: 'Thin universal card frame for dense module surfaces.',
      screenFamilies: ['module', 'dense', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_card_thin_9slice.png',
      notes: ['Primary reusable frame; define slice margins when real art lands.'],
    },
    {
      id: 'ui.chrome.frameCardMedium9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_card_medium_9slice',
      intendedUse: 'Medium-weight frame for major panel groups.',
      screenFamilies: ['module', 'hero', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_card_medium_9slice.png',
      notes: ['Sits between thin card and heavy ritual framing.'],
    },
    {
      id: 'ui.chrome.frameCardHeavy9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_card_heavy_9slice',
      intendedUse: 'Heavy frame for marquee hero callouts and shrine-like cards.',
      screenFamilies: ['hero', 'ritual', 'world'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_card_heavy_9slice.png',
      notes: ['Should feel ceremonial without carrying baked text.'],
    },
    {
      id: 'ui.chrome.frameButton9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_button_9slice',
      intendedUse: 'Button frame for reusable clickable controls across modules.',
      screenFamilies: ['global', 'module', 'dense'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_button_9slice.png',
      notes: ['Text remains DOM; art provides only structure and trim.'],
    },
    {
      id: 'ui.chrome.frameTooltip9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_tooltip_9slice',
      intendedUse: 'Tooltip frame for readable explanatory overlays.',
      screenFamilies: ['global', 'dense', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_tooltip_9slice.png',
      notes: ['Keeps text surfaces readable and stylized with one family.'],
    },
    {
      id: 'ui.chrome.frameModalScroll9',
      family: 'chrome',
      subfamily: 'frame',
      status: 'planned-missing',
      logicalName: 'frame_modal_scroll_9slice',
      intendedUse: 'Scroll-like modal frame for ritual and lore presentation.',
      screenFamilies: ['ritual', 'global', 'hero'],
      textless: true,
      tintable: true,
      nineSliceCandidate: true,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/frames/frame_modal_scroll_9slice.png',
      notes: ['Intended companion to legacy scroll motif reuse.'],
    },
    {
      id: 'ui.chrome.plaqueHeaderSmall',
      family: 'chrome',
      subfamily: 'plaque',
      status: 'planned-missing',
      logicalName: 'plaque_header_small',
      intendedUse: 'Compact section header plaque.',
      screenFamilies: ['dense', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/plaques/plaque_header_small.png',
      notes: ['Short headline treatment without embedded glyph text.'],
    },
    {
      id: 'ui.chrome.plaqueHeaderLarge',
      family: 'chrome',
      subfamily: 'plaque',
      status: 'planned-missing',
      logicalName: 'plaque_header_large',
      intendedUse: 'Large section title plaque for marquee rows.',
      screenFamilies: ['hero', 'world', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/plaques/plaque_header_large.png',
      notes: ['Pairs with small variant for hierarchy consistency.'],
    },
    {
      id: 'ui.chrome.plaqueInspector',
      family: 'chrome',
      subfamily: 'plaque',
      status: 'planned-missing',
      logicalName: 'plaque_inspector',
      intendedUse: 'Inspector/metadata plate behind stats and readouts.',
      screenFamilies: ['dense', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/plaques/plaque_inspector.png',
      notes: ['Should remain subtle to avoid fighting foreground text.'],
    },
    {
      id: 'ui.chrome.plaqueWorldLabel',
      family: 'chrome',
      subfamily: 'plaque',
      status: 'planned-missing',
      logicalName: 'plaque_world_label',
      intendedUse: 'World map/location label plaque.',
      screenFamilies: ['world', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/plaques/plaque_world_label.png',
      notes: ['Supports city/module labels over scenic backdrops.'],
    },
    {
      id: 'ui.chrome.ribbonBreadcrumbLong',
      family: 'chrome',
      subfamily: 'ribbon',
      status: 'planned-missing',
      logicalName: 'ribbon_breadcrumb_long',
      intendedUse: 'Long breadcrumb ribbon for pathing and context lines.',
      screenFamilies: ['world', 'module', 'global'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/ribbons/ribbon_breadcrumb_long.png',
      notes: ['Used where hierarchy/context labels need visual anchoring.'],
    },
    {
      id: 'ui.chrome.ribbonSectionShort',
      family: 'chrome',
      subfamily: 'ribbon',
      status: 'planned-missing',
      logicalName: 'ribbon_section_short',
      intendedUse: 'Short section ribbon for compact in-panel headings.',
      screenFamilies: ['dense', 'module', 'hero'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/ribbons/ribbon_section_short.png',
      notes: ['Should remain reusable across tabs, drawers, and popovers.'],
    },
    {
      id: 'ui.chrome.stampRecommendation',
      family: 'chrome',
      subfamily: 'ribbon',
      status: 'planned-missing',
      logicalName: 'stamp_recommendation',
      intendedUse: 'Recommendation stamp accent for advisor surfaces.',
      screenFamilies: ['global', 'dense', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/ribbons/stamp_recommendation.png',
      notes: ['Stamp form only; text lives in DOM copy.'],
    },
    {
      id: 'ui.chrome.stampWarning',
      family: 'chrome',
      subfamily: 'ribbon',
      status: 'planned-missing',
      logicalName: 'stamp_warning',
      intendedUse: 'Warning stamp accent for cautionary state callouts.',
      screenFamilies: ['global', 'dense', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: false,
      expectedPath: 'src/assets/ui/chrome/ribbons/stamp_warning.png',
      notes: ['Supports warning semantics without baking words into texture.'],
    },
  ],
};
