import type { UiAssetManifest } from '../types.js';

export const HERO_UI_ASSET_MANIFEST: UiAssetManifest = {
  family: 'hero',
  assets: [
    {
      id: 'ui.hero.cultivation.altarBase',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_altar_base',
      intendedUse: 'Base altar plane for cultivation hero composition.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_altar_base.png',
      notes: ['Layered kit part; not a flattened poster background.'],
    },
    {
      id: 'ui.hero.cultivation.orbCore',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_orb_core',
      intendedUse: 'Primary dantian orb core layer.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_orb_core.png',
      notes: ['Layered hero center element designed for tint + FX overlays.'],
    },
    {
      id: 'ui.hero.cultivation.orbRingOuter',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_orb_ring_outer',
      intendedUse: 'Outer orb ring accent for rotating hero compositions.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_orb_ring_outer.png',
      notes: ['Layered kit ring element; pairs with core and inner ring.'],
    },
    {
      id: 'ui.hero.cultivation.orbRingInner',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_orb_ring_inner',
      intendedUse: 'Inner orb ring detail for depth and parallax.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_orb_ring_inner.png',
      notes: ['Layered kit piece intended for independent motion/opacity.'],
    },
    {
      id: 'ui.hero.cultivation.auraWisp01',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_aura_wisp_01',
      intendedUse: 'Aura wisp pass one for cultivation hero envelope.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_aura_wisp_01.png',
      notes: ['Layered aura component; not a standalone full-scene texture.'],
    },
    {
      id: 'ui.hero.cultivation.auraWisp02',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_aura_wisp_02',
      intendedUse: 'Aura wisp pass two for composition variety.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_aura_wisp_02.png',
      notes: ['Companion layer with different silhouette cadence.'],
    },
    {
      id: 'ui.hero.cultivation.pedestalShadow',
      family: 'hero',
      subfamily: 'cultivation',
      status: 'planned-missing',
      logicalName: 'cultivation_pedestal_shadow',
      intendedUse: 'Grounding shadow layer beneath cultivation altar stack.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/cultivation/cultivation_pedestal_shadow.png',
      notes: ['Depth-control layer in the hero kit stack.'],
    },
    {
      id: 'ui.hero.heartlaw.sealPedestal',
      family: 'hero',
      subfamily: 'heartlaw',
      status: 'planned-missing',
      logicalName: 'heartlaw_seal_pedestal',
      intendedUse: 'Base pedestal for Heart Law seal compositions.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/heartlaw/heartlaw_seal_pedestal.png',
      notes: ['Layered kit base; supports independent ring/glyph overlays.'],
    },
    {
      id: 'ui.hero.heartlaw.sealRing',
      family: 'hero',
      subfamily: 'heartlaw',
      status: 'planned-missing',
      logicalName: 'heartlaw_seal_ring',
      intendedUse: 'Ring layer around active Heart Law seal.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/heartlaw/heartlaw_seal_ring.png',
      notes: ['Layered orbit element, intentionally text-free.'],
    },
    {
      id: 'ui.hero.heartlaw.glyphHaloSoft',
      family: 'hero',
      subfamily: 'heartlaw',
      status: 'planned-missing',
      logicalName: 'heartlaw_glyph_halo_soft',
      intendedUse: 'Soft glyph halo layer for Heart Law resonance emphasis.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/heartlaw/heartlaw_glyph_halo_soft.png',
      notes: ['Layered halo element for resonance pulses.'],
    },
    {
      id: 'ui.hero.heartlaw.sealPulseMask',
      family: 'hero',
      subfamily: 'heartlaw',
      status: 'planned-missing',
      logicalName: 'heartlaw_seal_pulse_mask',
      intendedUse: 'Pulse mask used to animate Heart Law seal intensity.',
      screenFamilies: ['hero', 'ritual'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/heartlaw/heartlaw_seal_pulse_mask.png',
      notes: ['Layered mask utility for rhythmic ritual pulses.'],
    },
    {
      id: 'ui.hero.world.forgeAvatarAnchor',
      family: 'hero',
      subfamily: 'world',
      status: 'planned-optional',
      logicalName: 'world_forge_avatar_anchor',
      intendedUse: 'Optional forge hero anchor kit for future world packet.',
      screenFamilies: ['world', 'hero', 'module'],
      textless: true,
      tintable: true,
      nineSliceCandidate: false,
      layeredKit: true,
      expectedPath: 'src/assets/ui/heroes/world/world_forge_avatar_anchor.png',
      notes: ['Optional future kit entry; not required for immediate rollout.'],
    },
  ],
};
