import type { ReleaseGateCheckId } from './releaseGateTypes.js';

export type ReleaseGateCheckManifestEntry = {
  checkId: ReleaseGateCheckId;
  order: number;
  title: string;
  packetOwners: string[];
  why: string;
  evidenceCommand: string;
  evidencePaths: string[];
  canEmitWaiverCandidateWarnings: boolean;
  failureAlwaysBlocker: boolean;
  canReturnPendingManual: boolean;
};

export const RELEASE_GATE_MANIFEST: ReadonlyArray<ReleaseGateCheckManifestEntry> = Object.freeze([
  {
    checkId: 'runtime_content_manifest',
    order: 1,
    title: 'Runtime Content Manifest',
    packetOwners: ['P0-01'],
    why: 'Ensures the playable artifact source tree contains every runtime JSON file the loader fetches.',
    evidenceCommand: 'npm run release:runtime-content-manifest:json',
    evidencePaths: ['public/cultivation_idle_content_bible_v1_config', 'docs/release/runtime_content_manifest.md'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'build_audit',
    order: 2,
    title: 'Build Warning Inventory',
    packetOwners: ['7.4a'],
    why: 'Ensures build blockers/warnings are explicitly classified before RC sign-off.',
    evidenceCommand: 'npm run release:build-audit:json',
    evidencePaths: ['docs/release/build_warning_inventory.md'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'content_validation',
    order: 3,
    title: 'Content Validation',
    packetOwners: ['core-content'],
    why: 'Validates authored content pack cross-references and semester-slice integrity.',
    evidenceCommand: 'npm run validate:content',
    evidencePaths: ['public/cultivation_idle_content_bible_v1_config'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'progression_contract',
    order: 4,
    title: 'Progression Contract Drift',
    packetOwners: ['1.1-1.8'],
    why: 'Prevents progression-truth drift between authored content and runtime surfaces.',
    evidenceCommand: 'builder:buildProgressionContract + collectProgressionDiagnostics',
    evidencePaths: ['src/systems/progression/contract', 'src/systems/progression/diagnostics'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'fresh_run_acceptance',
    order: 5,
    title: 'Fresh Run Acceptance',
    packetOwners: ['7.1'],
    why: 'Ensures new-life progression and final-truth checkpoints remain release-honest.',
    evidenceCommand: 'npm run release:fresh-run-report:json',
    evidencePaths: ['docs/release/qa/fresh_save_routes.md'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: true,
  },
  {
    checkId: 'migration_matrix',
    order: 6,
    title: 'Migration Matrix',
    packetOwners: ['7.2'],
    why: 'Verifies migration safety across canonical fixture classes and high-risk save variants.',
    evidenceCommand: 'npm run release:migration-matrix:json',
    evidencePaths: ['docs/release/migration_fixture_catalog.md'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'balance_regression',
    order: 7,
    title: 'Balance Regression',
    packetOwners: ['6.x', '7.3'],
    why: 'Guards pacing, throughput and AP/hour envelopes for semester release balancing.',
    evidenceCommand: 'npm run balance:report:json',
    evidencePaths: ['tmp-tests/scripts/balanceRegressionReport.js'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'route_comparison',
    order: 8,
    title: 'Route Comparison',
    packetOwners: ['7.3'],
    why: 'Ensures fresh/offline/reclaim route truth stays aligned with semester final-truth constraints.',
    evidenceCommand: 'npm run release:route-report:json',
    evidencePaths: ['docs/release/qa'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'runtime_diagnostics',
    order: 9,
    title: 'Runtime Diagnostics',
    packetOwners: ['7.4c'],
    why: 'Catches runtime validation errors and health regressions before RC.',
    evidenceCommand: 'npm run release:runtime-diagnostics:json',
    evidencePaths: ['src/services/diagnostics/runValidation.ts'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'mp5_reset_memory',
    order: 10,
    title: 'MP5 Reset and Prestige Memory',
    packetOwners: ['MP5'],
    why: 'Ensures reincarnation reset truth, bounded memory ledger fields, and MP5 memory effects remain source-owned.',
    evidenceCommand: 'npm run test:mp5',
    evidencePaths: ['src/services/prestige', 'src/systems/prestige/prestigeMemory.ts', 'tests/contracts/mp5PrestigeMemoryContract.test.ts'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'mp5_offline_trust',
    order: 11,
    title: 'MP5 Offline Trust Report',
    packetOwners: ['MP5'],
    why: 'Ensures Training and Dao Heart offline catch-up remains bounded, explainable, and non-combat.',
    evidenceCommand: 'npm run test:mp5',
    evidencePaths: ['src/services/time/OfflineCatchup.ts', 'src/systems/offline/offlineCatchupSurface.ts', 'tests/contracts/mp5OfflineTrustSurface.test.ts'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'mp5_telemetry_schema',
    order: 12,
    title: 'MP5 Telemetry Schema',
    packetOwners: ['MP5'],
    why: 'Ensures Training, Dao Heart, reset, and prestige-memory telemetry names stay exportable and schema-owned.',
    evidenceCommand: 'npm run validate:balance-telemetry',
    evidencePaths: ['src/services/events/GameEvents.ts', 'src/services/diagnostics/balanceTelemetrySchema.ts', 'tests/integration/mp5TelemetryHookCoverage.test.ts'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'mp5_balance_simulations',
    order: 13,
    title: 'MP5 Balance Simulations',
    packetOwners: ['MP5'],
    why: 'Covers Path/Root/Law first-gate and Foundation reclaim routes plus named exploit cases without retuning constants.',
    evidenceCommand: 'npm run release:mp5-balance-simulations:json',
    evidencePaths: ['src/systems/balance/mp5BalanceSimulation.ts', 'tests/contracts/mp5BalanceSimulation.test.ts'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'mp5_prestige_runtime_audit',
    order: 14,
    title: 'MP5 Prestige Runtime Audit',
    packetOwners: ['MP5'],
    why: 'Ensures MP5 prestige nodes are classified as visible, hidden, deferred, or unsupported truthfully.',
    evidenceCommand: 'npm run release:prestige-runtime-audit:json',
    evidencePaths: ['public/cultivation_idle_content_bible_v1_config/prestige_store.json', 'scripts/release/buildPrestigeRuntimeEffectAudit.ts'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
  {
    checkId: 'vocabulary_audit',
    order: 15,
    title: 'Vocabulary Audit',
    packetOwners: ['7.5a'],
    why: 'Prevents stale placeholder/debug copy regressions on tracked live surfaces.',
    evidenceCommand: 'npm run release:vocab-audit:json',
    evidencePaths: ['docs/release/vocabulary_audit.md'],
    canEmitWaiverCandidateWarnings: true,
    failureAlwaysBlocker: false,
    canReturnPendingManual: false,
  },
  {
    checkId: 'full_test_suite',
    order: 16,
    title: 'Full Test Suite',
    packetOwners: ['7.4d-7.5d'],
    why: 'Authoritative umbrella proof for test-first release-critical checks.',
    evidenceCommand: 'npm run test',
    evidencePaths: ['tests/contracts', 'tests/integration/release', 'tests/migrations'],
    canEmitWaiverCandidateWarnings: false,
    failureAlwaysBlocker: true,
    canReturnPendingManual: false,
  },
]);

export const RELEASE_GATE_CHECK_IDS = RELEASE_GATE_MANIFEST.map((entry) => entry.checkId);
