export {
  DEFAULT_PERF_CONFIG,
  PERF_LOCAL_STORAGE_KEY,
  PERF_QUERY_PARAM,
  detectPerfConfig,
  type PerfConfig,
  type PerfEnableSource,
} from './perfConfig.js';
export { PERF_LABELS, type PerfLabel } from './perfLabels.js';
export {
  configurePerfForTests,
  endScenario,
  exportPerfSnapshot,
  getPerfConfig,
  incrementCounter,
  initializePerformanceInstrumentation,
  installPerfWindowDebug,
  isPerfEnabled,
  mark,
  measure,
  now,
  recordEvent,
  recordMeasure,
  resetPerfSnapshot,
  startPerformanceObservers,
  startScenario,
  startTimer,
  stopPerformanceObservers,
  time,
  timeAsync,
  type PerfCounterRecord,
  type PerfEventRecord,
  type PerfExport,
  type PerfLongAnimationFrameRecord,
  type PerfLongTaskRecord,
  type PerfMeasureRecord,
  type PerfRenderRecord,
  type PerfScenarioRecord,
} from './perfLogger.js';
