import React from 'react';
import type { RuinsExactSurfaceV1, RuinsKitEquipmentSlotId } from '../types.js';
import { RUINS_EXACT_ASSETS } from '../ruinsExactAssetRegistry.js';

export interface RuinsKitCardProps {
  kit: RuinsExactSurfaceV1['kitCard'];
  onOpenMedicinePouch?: () => void;
  onOpenLoadout?: () => void;
  onOpenAiProfile?: () => void;
  onOpenEquipmentSlot?: (slotId: RuinsKitEquipmentSlotId) => void;
}

export function RuinsKitCard({ kit, onOpenMedicinePouch, onOpenLoadout, onOpenAiProfile, onOpenEquipmentSlot }: RuinsKitCardProps) {
  return React.createElement('section', { className: 'ruinsKitCard', 'data-testid': 'ruins-kit-card', 'aria-label': 'Ruin Kit' },
    React.createElement('header', { className: 'ruinsKitCard__header' }, React.createElement('h3', { className: 'ruinsKitCard__title', 'data-testid': 'ruins-kit-title' }, kit.title), kit.stamp ? React.createElement('span', { className: 'ruinsKitCard__stamp', 'data-testid': 'ruins-kit-stamp', 'data-tone': kit.stamp.tone }, kit.stamp.label) : null),
    React.createElement('div', { className: 'ruinsKitCard__setupRows' }, ...kit.setupRows.map((row) => React.createElement('button', { key: row.id, type: 'button', className: 'ruinsKitCard__setupRow', 'data-testid': `ruins-kit-setup-row-${row.id}`, onClick: row.id === 'loadoutSet' ? onOpenLoadout : row.id === 'aiProfile' ? onOpenAiProfile : undefined, disabled: (row.id === 'loadoutSet' ? !onOpenLoadout : row.id === 'aiProfile' ? !onOpenAiProfile : true), 'aria-label': `${row.label}: ${row.value}` }, React.createElement('span', { className: 'ruinsKitCard__iconDock' }, React.createElement('img', { src: RUINS_EXACT_ASSETS.icons.kit[row.iconKey as keyof typeof RUINS_EXACT_ASSETS.icons.kit], alt: '' })), React.createElement('span', { className: 'ruinsKitCard__rowLabel' }, row.label), React.createElement('span', { className: 'ruinsKitCard__rowValue' }, row.value), row.id === 'loadoutSet' ? React.createElement('span', { className: 'ruinsKitCard__rowAction', 'aria-hidden': 'true' }, '+') : null))),
    ...kit.statSections.map((section) => React.createElement('section', { key: section.id, className: `ruinsKitCard__section ruinsKitCard__section--${section.id}`, 'data-testid': `ruins-kit-stat-section-${section.id}` }, React.createElement('h4', { className: 'ruinsKitCard__sectionTitle' }, section.title), ...section.rows.map((row) => React.createElement('div', { key: row.id, className: 'ruinsKitCard__statRow', 'data-testid': `ruins-kit-stat-row-${row.id}` }, React.createElement('span', { className: 'ruinsKitCard__iconDock' }, React.createElement('img', { src: RUINS_EXACT_ASSETS.icons.kit[row.iconKey as keyof typeof RUINS_EXACT_ASSETS.icons.kit], alt: '' })), React.createElement('span', { className: 'ruinsKitCard__rowLabel' }, row.label), React.createElement('span', { className: 'ruinsKitCard__rowValue' }, row.value))))),
    React.createElement('section', { className: 'ruinsKitCard__section ruinsKitCard__section--pouch' }, React.createElement('h4', { className: 'ruinsKitCard__sectionTitle' }, 'Medicine Pouch'), React.createElement('div', { className: 'ruinsKitCard__pouchRow', 'data-testid': 'ruins-kit-pouch-row' }, React.createElement('span', { className: 'ruinsKitCard__iconDock' }, React.createElement('img', { src: RUINS_EXACT_ASSETS.icons.kit[kit.medicinePouch.iconKey as keyof typeof RUINS_EXACT_ASSETS.icons.kit], alt: '' })), React.createElement('span', { className: 'ruinsKitCard__pouchValue' }, kit.medicinePouch.value), React.createElement('button', { type: 'button', className: 'ruinsKitCard__pouchAction', 'data-testid': 'ruins-kit-pouch-action', disabled: !kit.medicinePouch.action.enabled, onClick: kit.medicinePouch.action.enabled ? onOpenMedicinePouch : undefined, 'aria-label': kit.medicinePouch.action.ariaLabel }, kit.medicinePouch.action.label))),
    React.createElement('section', { className: 'ruinsKitCard__section ruinsKitCard__section--equipment' }, React.createElement('h4', { className: 'ruinsKitCard__sectionTitle' }, 'Equipment'), React.createElement('div', { className: 'ruinsKitCard__equipmentGrid', 'data-testid': 'ruins-kit-equipment-grid' }, ...kit.equipmentGrid.map((slot) => React.createElement('button', { key: slot.slotId, type: 'button', className: 'ruinsKitCard__equipmentCell', 'data-testid': `ruins-kit-equipment-slot-${slot.slotId}`, onClick: onOpenEquipmentSlot ? () => onOpenEquipmentSlot(slot.slotId) : undefined, disabled: !onOpenEquipmentSlot, 'aria-label': `${slot.label}: ${slot.value}` }, React.createElement('img', { className: 'ruinsKitCard__equipmentIcon', src: RUINS_EXACT_ASSETS.icons.kit[slot.iconKey as keyof typeof RUINS_EXACT_ASSETS.icons.kit], alt: '', 'aria-hidden': 'true' }), React.createElement('span', { className: 'ruinsKitCard__sr' }, `${slot.label} ${slot.value}`))))),
  );
}
